name = "MyUtilities"
uuid = "6510ae6a-d2c5-41ab-bd9f-56601e1ee226"
authors = ["abbaa90 <abbaa90@fu-berlin.de> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
